### ISSUE TITLE
Branches 

### ISSUE THREAD

**Issue by korvinos** [korvinos/django-fun#13]
If you have questions or bugs with git branches  just use this chat

docs: https://git-scm.com/docs/git-branch
CIA tutorial: https://wikileaks.org/ciav7p1/cms/space_1736707.html
a popular model of code development with git: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by ingrih** [comment]
Here's one I found: https://backlog.com/git-tutorial/en/stepup/stepup1_1.html

**Comment by AlfaAli** [comment]
Great I created and push a develop branch called devel_Alfa as described here:
 https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by ingrih** [comment]
I have made a branch for me and Artem too. 

**In general:** 
New branch: _git branch <name_of_new_branch>_
Move to branch: _git checkout <name_of_branch>_
Add to GitHub: _git push origin <name_of_your_new_branch>_
After changing a file: _git add <...>
git commit -am 'text...'_
Going back to master-branch to merge: _git checkout master_
_git merge <...>_
If the file has been changed in several branches and we try to merge more than one of those edits into master we will get conflict. -> must be handled manually, then _git add <...> and commit._

**Comment by AlfaAli** [comment]
wher are you meeting? Im looking for you
